### ISSUE TITLE
Spicetify Marketplace not loading due to not finding manifests and issues with `createPortal`

### ISSUE THREAD

**Issue by AntiApple4life** [spicetify/marketplace#218]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716
- Spicetify version: 2.10.1
```

### 📝 Description

Install spicetify, install spicetify marketplace, launch spotify and open marketplace tab

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/59315931/172476117-74eda9ac-b7ed-44e0-9a1d-80e28d0fc8df.png)

**Comment by Anti-Apple4life** [comment]
![image](https://user-images.githubusercontent.com/59315931/172482382-3c2632a7-7060-4956-b7dc-4346551afc46.png)
They do support it

**Comment by theRealPadster** [comment]
It may say it's supported, but I've seen a ton of people in the discord have it not work. I don't think anything was done to make sure the hook regex worked on both the old and new versions.
