### ISSUE TITLE
Spotify Marketplace loads an empty page

### ISSUE THREAD

**Issue by svr333** [spicetify/marketplace#385]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.99.878.g1e4ccc6e
- Spicetify version: 2.14.2
- Windows 11 22H2
```

### 📝 Description

*Apologies if this is a known issue or if I'm posting in a wrong repo*

The marketplace doesn't really load for me anymore, it just shows an empty page (see screenshot).
When I re-installed spicetify on a new environment a few days ago, I installed the marketplace and downloaded a few snippets and extensions. Marketplace is the only custom app installed. I haven't really touched it since then but now when I try to see my installed snippets or look for more it just shows an empty page.
Reusing the installation script did not work

If more info is required, feel free to mention me for a faster reply.

### 📸 Screenshots

![Screenshot_1](https://user-images.githubusercontent.com/35664724/204544890-f1431692-1151-4fb6-838b-a10ea91f372f.png)

**Comment by kyrie25** [comment]
Upgrade Spicetify and then run `spicetify backup apply` afterwards
