### ISSUE TITLE
Star count incorrect for all items in store

### ISSUE THREAD

**Issue by mpusch88** [spicetify/marketplace#597]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit) 1.2.20.1210.g2a8a8a57
- Spicetify version: v2.23.2
```

### 📝 Description

In order to help people find the best themes and extensions, it would be great if there were a working way to see how many people have favorited each item.

Currently when looking in the Spicetify marketplace, all the top entries in the themes and extensions categories have exactly the same number of stars.

To reproduce

- open the Marketplace tab in Spotify, and view the Extensions or Themes pages (see screenshot)

To me it seems highly unlikely that the top items would have exactly the same number of likes - I feel like there must be something wrong with the logic on how this is being handled.

It would be great if this feature were improved.

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/11446016/b65c003a-7894-4a42-9fab-0bb70b1c9a64)

**Comment by CharlieS1103** [comment]
It uses the GitHub star rating and many of the top extensions are located in the same repository, its not an error.
