### ISSUE TITLE
Error while instaling

### ISSUE THREAD

**Issue by PwccaCode** [spicetify/marketplace#758]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (32 bit) 1.2.38.720.ga4a70a0e
- Spicetify version: 2.36.11
```

### 📝 Description

When running the install script i get

Setting up...
Removing and creating Marketplace folders...
New-Item : Illegal characters in path.
At line:32 char:1
+ New-Item -Path $marketAppPath, $marketThemePath -ItemType 'Directory' ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (C:\Users\Leo\ni\CustomApps:String) [New-Item], ArgumentExceptio
   n
    + FullyQualifiedErrorId : ItemExistsArgumentError,Microsoft.PowerShell.Commands.NewItemCommand

### 📸 Screenshots

![image](https://github.com/spicetify/spicetify-marketplace/assets/51799102/8f03b296-75ea-4be7-aefe-ba494f70d26b)

**Comment by rxri** [comment]
well, something's up with your path because it didn't even put it into the `%appdata%\spicetify`... you may need to install it manually, sorry

**Comment by ayamkv** [comment]
i have the same issue aswell, how do i install this manually??
![image](https://github.com/user-attachments/assets/761e1498-d299-4a79-a8da-e8b70277aaef)

**Comment by PwccaCode** [comment]
simply start spotify once before trying to install, also make sure you are not openning powershell as administrator.

this issue is resolved please close it
