### ISSUE TITLE
Marketplace icon in the wrong place after update

### ISSUE THREAD

**Issue by RottenCarrot21** [spicetify/marketplace#766]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.38.720.ga4a70a0e
- Spicetify version: v2.36.11
```

### 📝 Description

The marketplace icon is in the wrong place after update. It is same with any theme.

Open spotify normally

### 📸 Screenshots

![image](https://github.com/spicetify/marketplace/assets/139256091/0e862530-c234-4974-8820-680a746cfe28)

**Comment by rxri** [comment]
Not related to marketplace. Already fixed upstream in cli repo. Wait for spicetify update
