### ISSUE TITLE
Marketplace Icon is offset

### ISSUE THREAD

**Issue by JGabT** [spicetify/marketplace#767]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.38.720.ga4a70a0e
- Spicetify version: 2.36.11
```

### 📝 Description

Using it normally, and it updated one time (forgot which version), how do I fix this?

### 📸 Screenshots

![image](https://github.com/spicetify/marketplace/assets/9552055/0bdf06e1-ea05-437f-9ea0-6fa7c771f6e0)
![image](https://github.com/spicetify/marketplace/assets/9552055/ddb0f22c-0568-4352-857d-82d6c604cb65)

**Comment by rxri** [comment]
Fixed upstream in cli. Wait for an update.
