### ISSUE TITLE
Marketplace won't build locally with current main code

### ISSUE THREAD

**Issue by zhngharry** [spicetify/marketplace#782]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: Spotify for Windows (64 bit), 1.2.39.578.g0ea3f38b
- Spicetify version: v2.36.12
```

### 📝 Description

When cloning the current main branch of spicetify and trying to build it locally, Marketplace won't load. I have discovered that any version of the main branch **since** (including) commit 15900b9 (PR #759) causes the error locally, and any version prior to that still works.

Steps to reproduce:

Clone repo

run pnpm build:local

Copy files from dist folder into spicetify marketplace folder

run spicetify apply in terminal

observe marketplace in client

**Comment by rxri** [comment]
try now

**Comment by zhngharry** [comment]
> try now

works as expected now, thanks for being so quick ^^
