### ISSUE TITLE
Gnome Crash

### ISSUE THREAD

**Issue by ch5rus** [spicetify/marketplace#788]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: latest from yay as of 17.6.24 dd.mm.yy
- Spicetify version: latest from yay as of 17.6.24 dd.mm.yy
-Spicetify marketplace installed through curl, not yay
-4gb ram
-EndeavourOS
-Gnome 46 DE
```

### 📝 Description

-Open spotify
-Open marketplace
-Loads, noticably slows, scroll and it crashes

### 📸 Screenshots

![Screenshot from 2024-06-17 19-30-19](https://github.com/spicetify/marketplace/assets/159018522/b2fdb286-acee-4a66-88b1-e491db9478ff)
[Screencast from 2024-06-17 19-34-51.webm](https://github.com/spicetify/marketplace/assets/159018522/fcbdc0cd-96bb-413c-8153-75b191561ae2)

**Comment by Delusoire** [comment]
what extensions, apps and themes do you use?

**Comment by ch5rus** [comment]
my hardware is ass but no way spicetify is using all that
additional notes: spotify was working fine before, after yay installation

**Comment by ch5rus** [comment]
> what extensions, apps and themes do you use?

none so far, i just installed spicetify using yay and marketplace using curl

**Comment by ch5rus** [comment]
fully solved, i installed everything i wanted with no other apps open and now it works perfectly, however it might be useful to look into why the marketplace uses so much memory on a fresh install? might just be a one off, my craptop is a bit schizo

**Comment by ch5rus** [comment]
fully solved, just dont use gnome lmfao
