### ISSUE TITLE
"No page was found" error on most recent extensions

### ISSUE THREAD

**Issue by johnnyjohnboyboy** [spicetify/marketplace#790]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.8.923.g4f94bf0d
- Spicetify version: 2.25.3
```

### 📝 Description

I went to Marketplace and clicked on one of the recent extensions with "Last updated June 22, 2024" on them. When I click on them, they all say "No page was found." I expected to see the page for those extensions when I clicked on them.

### 📸 Screenshots

![image](https://github.com/spicetify/marketplace/assets/53444998/817bd69f-e038-40bc-8920-bea892ac6be3)

**Comment by rxri** [comment]
Means there's no readme available. Extensions made by spicetify team do not have one.

**Comment by johnnyjohnboyboy** [comment]
Ah, thanks for clarifying.
