### ISSUE TITLE
Close button on View Snippet is not clickable

### ISSUE THREAD

**Issue by Ender-Wang** [spicetify/marketplace#799]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.41.434.g39a25e2c
- Spicetify version: v2.36.14
```

### 📝 Description

Click the close button does not do anything.

### 📸 Screenshots

![CleanShot_2024-07-05_23-01-41](https://github.com/spicetify/marketplace/assets/33310255/7e2375f9-80ae-49ba-96bb-4a8940a17db3)

**Comment by rxri** [comment]
Works just fine.
