### ISSUE TITLE
Add more information to custom app manifest

### ISSUE THREAD

**Issue by Gerg-L** [spicetify/marketplace#809]
### 📝 Provide a description of the new feature

I'm currently working on implementing automatic creation of extensions, themes, apps, and snippets for nixos
at my project here: <https://github.com/Gerg-L/spicetify-nix/>

I'm already done with extensions,themes, and snippets parsing the manifest with similar logic to marketplace

however for custom apps there isn't enough information in the manifest.
the `branch` option already exists
all I should need is a `main` option similar to extensions which points to the directory the app is in

this would also be useful in the future if/when marketplace is able to install customApps itself

**Comment by rxri** [comment]
99% of custom apps do not have manifest and do not bother about it because you can't install custom apps via marketplace so I don't really see a point in it

**Comment by Gerg-L** [comment]
Alright, worth asking

**Comment by Gerg-L** [comment]
Can I ask why customApps aren't going to be supported?

**Comment by rxri** [comment]
> Can I ask why customApps aren't going to be supported?

Limitation of how custom apps were made working in v2
