### ISSUE TITLE
Marketplace crashes my app?

### ISSUE THREAD

**Issue by LucaButtini** [spicetify/marketplace#816]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version:Spotify per Windows (64 bit) 1.2.43.420.gc7b23f70
- Spicetify version:v2.37.0
```

### 📝 Description

I installed the marketplace and spotify keeps closing at random. 
I alreay tried reinstalling everything and every time I install the marketplace it crashes.
Am I the only one with this problem?
Thanks for the assistance

**Comment by rxri** [comment]
Can't reproduce. Please join our discord server for further help

**Comment by LucaButtini** [comment]
I found out it is my normal spotify even without spicetify that crashes. I wrote it in the discord
