### ISSUE TITLE
Broken on latest spotify build

### ISSUE THREAD

**Issue by ItzELECTR0** [spicetify/marketplace#817]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.44.405.g81fd6352 on Windows (64 bit)
- Spicetify version: v2.37.0
```

### 📝 Description

After updating Spotify, the marketplace along with everything installed from it stopped working (Except the theme, that still works)
The option to open the marketplace is gone as if uninstalled, even right after installing through terminal.
While extensions do not work at all, it seems snippets installed through the marketplace before updating still work.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/60f537bc-7579-40ba-b4fd-c81b953d4f0d)

**Comment by rxri** [comment]
Reinstall spotify or check sidebar config. Spicetify is clearly injected because of the topbar icons I can see in the screenshot. Regardless, your issue is not an issue in spicetify.

**Comment by ItzELECTR0** [comment]
> Reinstall spotify or check sidebar config.

I did reinstall Spotify, Spicetify and the marketplace multiple times.

> Spicetify is clearly injected because of the topbar icons I can see in the screenshot.

I've specified that Spicetify, themes and snippets still work. It's the extensions and marketplace that don't.

> Regardless, your issue is not an issue in spicetify.

As stated, this is not a Spicetify issue, this is an issue with the marketplace specifically. That's why I reported the issue here.
