### ISSUE TITLE
Marketplace is broken on latest Spotify update

### ISSUE THREAD

**Issue by ItzELECTR0** [spicetify/marketplace#818]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.44.405.g81fd6352 on Windows (64 bit)
- Spicetify version: v2.37.0
```

### 📝 Description

After updating Spotify, the marketplace along with all extensions installed from it stopped working.
Spicetify itself along with themes and snippets installed from the marketplace still work
The option to open the marketplace is gone as if uninstalled, even right after installing through terminal.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/71e19583-aa0e-432a-945b-f25177300f59)

**Comment by ItzELECTR0** [comment]
> Reinstall spotify or check sidebar config.

I did reinstall Spotify, Spicetify and the marketplace multiple times.

> Spicetify is clearly injected because of the topbar icons I can see in the screenshot.

I've specified that Spicetify, themes and snippets still work. It's the extensions and marketplace that don't.

> Regardless, your issue is not an issue in spicetify.

As stated, this is not a Spicetify issue, this is an issue with the marketplace specifically. That's why I reported the issue here.

**Comment by rxri** [comment]
Okay, I just have noticed that you're on 1.2.44. Spicetify does not support 1.2.44 as mentioned in release notes. Please wait for appropriate update.

**Comment by rxri** [comment]
Fixed with https://github.com/spicetify/cli/releases/tag/v2.37.1

**Comment by ItzELECTR0** [comment]
Fire ❤️‍🔥
