### ISSUE TITLE
Install/Enable multiple themes at the same time

### ISSUE THREAD

**Issue by ItzELECTR0** [spicetify/marketplace#819]
### 📝 Provide a description of the new feature

Feature inspired by BetterDiscord and Vencord, allows the user to install and use more than one theme at the same time. To mix and match looks. Themes would override each other based on which is enabled first and modify each other's values, allowing for some really cool looking results.

### ➕ Additional Information

Example with what happens in Vencord when SoftX and FrostedGlass are enabled at the same time
(In that order)

![image](https://github.com/user-attachments/assets/36635ee3-91fe-4f8b-a758-4b350cf574ae)
![image](https://github.com/user-attachments/assets/86d4f9d5-4362-4a9d-b820-03b8730dc613)

**Comment by rxri** [comment]
Won't happen because a lot of themes have its own javascript (where in discord they don't) to work. Themes would need to work with each other to make this happen which makes it a lot of work, plus themes modify a lot of classes. Marketplace in v2 is in maintenance mode anyways

**Comment by ItzELECTR0** [comment]
Fair, but it could work like an experimental setting only available for CSS only themes.
