### ISSUE TITLE
cant download 

### ISSUE THREAD

**Issue by 0lav8** [spicetify/marketplace#835]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.45.454.gc16ec9f6
- Spicetify version: v2.38.3
```

### 📝 Description

everytime i install the code and get to marketplace, it says set spotify path manually many times then says done, but nothing happens

### 📸 Screenshots

![Screenshot 2024-09-15 034708](https://github.com/user-attachments/assets/34083082-805f-44b9-8f5e-4ad6250f8cf7)

**Comment by sanoojes** [comment]
Please manually set “spotify_path” in config-xpui.ini

**Comment by sanoojes** [comment]
Or run Spicetify Installation Script it will add it automaticlly ```powershell
iwr -useb https://raw.githubusercontent.com/spicetify/cli/main/install.ps1 | iex
```

**Comment by 0lav8** [comment]
from where exactly can i add it? i'm sorry but i'm not able to figure out where to find the config-xpui.ini

**Comment by sanoojes** [comment]
> from where exactly can i add it? i'm sorry but i'm not able to figure out where to find the config-xpui.ini

its available at `%appdata%/spicetify`

**Comment by rxri** [comment]
Issues are not for help
