### ISSUE TITLE
After installing Spicetify Marketplace, theme "marketplace" not found

### ISSUE THREAD

**Issue by italiatroller-1990** [spicetify/marketplace#842]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.45.454.gc16ec9f6
- Spicetify version: 2.38.4
- OS: Arch Linux
```

### 📝 Description

Encountered this after installing spicetify marketplace

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/8cdeaa57-b8d8-425c-8d21-7ac62c9a882a)
![image](https://github.com/user-attachments/assets/dc41016c-8f65-4fc5-a3b7-2ff1a60cc697)

**Comment by rxri** [comment]
Then install it again with marketplace install script

**Comment by italiatroller-1990** [comment]
nevermind, made the marketplace folder on the themes folder and it works
