### ISSUE TITLE
No "Marketplace" button after installing Spicetify

### ISSUE THREAD

**Issue by XdekTV** [spicetify/marketplace#850]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.5.1006.g22820f93
- Spicetify version: v2.38.4
- System: Modified Windows 10 IoT LTSC Enterprise 21H2
```

### 📝 Description

When installing Spicetify, marketplace doesn't show up, even when installing it manually.

### 📸 Screenshots

![obraz](https://github.com/user-attachments/assets/fab82129-ddcc-4b76-bee3-792c7ffc994b)

**Comment by rxri** [comment]
You're on 1.2.5. Spicetify does not support this version since ever.
