### ISSUE TITLE
After installation can't find Marketplace button

### ISSUE THREAD

**Issue by GreeningSiren** [spicetify/marketplace#855]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: I don't know where to find but should be latest according to website
-             Edit: Found to be `1.2.48.405.gf2c48e6f`
- Spicetify version: v2.38.4
```

### 📝 Description

Downloaded spicetify and spicetify marketplace. Installer asked for `Local theme found
Do you want to replace it with a placeholder to install themes from the Marketplace?
[Y] Yes  [N] No  [?] Help (default is "Y"):`, said yes. Screen turned to green mess and either home or marketplace button can't be found

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/77fe2014-644b-4d25-a32b-414c48101136)

**Comment by rxri** [comment]
Well, you had Dribblish installed before, so you need to remove it. https://github.com/spicetify/marketplace/wiki/Development#manual-reset

**Comment by GreeningSiren** [comment]
I'm still confused. What exactly do I need to do?

**Comment by GreeningSiren** [comment]
Golly gee I did it
