### ISSUE TITLE
No README File was found

### ISSUE THREAD

**Issue by RobyOneKenoby112** [spicetify/marketplace#859]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.49.439.gfae492c7
- Spicetify version: 2.38.4
- Laptop ASUS ROG G713RM
```

### 📝 Description

Every time i click on any extension it shows this red message: No README file was found

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/068870aa-c032-4e5a-8246-9cfe2e622b2b)

**Comment by RobyOneKenoby112** [comment]
I want to know how to see the full text under the stars number: "Videos are unable to play in some..."

**Comment by rxri** [comment]
Hover on the card and you will have install button in right bottom corner
