### ISSUE TITLE
Fix Extension Buttons

### ISSUE THREAD

**Issue by rahaaatul** [spicetify/marketplace#870]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.52.442.g01893f92
Spicetify v2.38.5
xpui_2024-12-02_1733143341811_01893f9
cef_130.1.16+g5a7e5ed+chromium-130.0.6723.117
Runtime: Chrome
Build System: Bazel
```

### 📝 Description

- `bookmark.js` and `popupLyrics.js` button does not look similar to other buttons.
- Other buttons are far away from home button.

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/99c4aa51-72aa-4fbd-848c-04996dbdabec)

**Comment by rxri** [comment]
extensions decide on their icons.

**Comment by rahaaatul** [comment]
> extensions decide on their icons.

But aren't they shipped with spicetify itself? they are spicetify's extensions, right?
