### ISSUE TITLE
Shuffle+:  TypeError: Cannot destructure property 'operation' of 't' as it is undefined.

### ISSUE THREAD

**Issue by rahaaatul** [spicetify/marketplace#871]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
Spotify for Windows (64 bit)
1.2.52.442.g01893f92
Spicetify v2.38.5
xpui_2024-12-02_1733143341811_01893f9
cef_130.1.16+g5a7e5ed+chromium-130.0.6723.117
Runtime: Chrome
Build System: Bazel
```

### 📝 Description

I try to shuffle **artist** with Shuffle+ and then I get this error:

```js
TypeError: Cannot destructure property 'operation' of 't' as it is undefined.
```

### 📸 Screenshots

![image](https://github.com/user-attachments/assets/860269fe-85c3-4d24-a7ef-0bf9adc05f8c)

**Comment by rxri** [comment]
not related to marketplace

**Comment by rahaaatul** [comment]
> not related to marketplace

can you help me with what it is related to, please?

**Comment by rxri** [comment]
It has been already fixed in the repo.

**Comment by rahaaatul** [comment]
> It has been already fixed in the repo.

thank you miss ririxi. you rock!
